
class Cast {

  List<Actor> actores = new List();

  Cast.fromJsonList(List<dynamic> miJsonList){
    if(miJsonList == null) return;

    miJsonList.forEach((i){
      final actor = Actor.fromJsonMap(i);
      actores.add(actor);
    });
  }
  
}
// Generated by https://quicktype.io

class Actor {
  int castId;
  String character;
  String creditId;
  int gender;
  int id;
  String name;
  int order;
  String profilePath;

  Actor({
    this.castId,
    this.character,
    this.creditId,
    this.gender,
    this.id,
    this.name,
    this.order,
    this.profilePath,
  });

  Actor.fromJsonMap(Map<String, dynamic> myJson){
    castId      = myJson['cast_id'];
    character   = myJson['character'];
    creditId    = myJson['credit_id'];
    gender      = myJson['gender'];
    id          = myJson['id'];
    name        = myJson['name'];
    order       = myJson['order'];
    profilePath = myJson['profile_path'];
  }

  getFoto() {
    if (profilePath == null) {
      return "https://pics.filmaffinity.com/Avatar-208925608-large.jpg";
    } else {
      return "https://image.tmdb.org/t/p/original/$profilePath";
    }
  }
}

