// Generated by https://quicktype.io
//paste JSON as code
//Respuesta

class Peliculas {
  List<Pelicula> itemPelicula = new List();

  //Peliculas();

  Peliculas.fromJsonList(List<dynamic> jsonList) {
    if(jsonList == null) return;

    for (var item in jsonList) {
      final pelicula = new Pelicula.fromJsonMap(item);
      itemPelicula.add(pelicula);
    }
  }
}

class Pelicula {
  String uniqueId;
  double popularity;
  int voteCount;
  bool video;
  String posterPath;
  int id;
  bool adult;
  String backdropPath;
  String originalLanguage;
  String originalTitle;
  List<int> genreIds;
  String title;
  double voteAverage;
  String overview;
  String releaseDate;

  Pelicula({
    this.video,
    this.posterPath,
    this.id,
    this.adult,
    this.backdropPath,
    this.originalLanguage,
    this.genreIds,
    this.title,
    this.voteAverage,
    this.overview,
    this.releaseDate,
    this.originalTitle,
    this.popularity,
    this.voteCount,
  });

  Pelicula.fromJsonMap(Map<String, dynamic> jsonRigo) {
    id               = jsonRigo['id'];
    video            = jsonRigo['video'];
    adult            = jsonRigo['adult'];
    title            = jsonRigo['title'];
    genreIds         = jsonRigo['genre_ids'].cast<int>();
    overview         = jsonRigo['overview'];
    voteCount        = jsonRigo['vote_count'];
    popularity       = jsonRigo['popularity'] / 1;
    posterPath       = jsonRigo['poster_path'];
    releaseDate      = jsonRigo['release_date'];
    voteAverage      = jsonRigo['vote_average'] / 1;
    backdropPath     = jsonRigo['backdrop_path'];
    originalTitle    = jsonRigo['original_title'];
    originalLanguage = jsonRigo['original_language'];
  }

  getPosterImg() {
    if (posterPath == null) {
      return "https://image.tmdb.org/t/p/original/wwemzKWzjKYJFfCeiB57q3r4Bcm.png";
    } else {
      return "https://image.tmdb.org/t/p/original/$posterPath";
    }
  }

  getbackGroundImg() {
    if (posterPath == null) {
      return "https://image.tmdb.org/t/p/original/wwemzKWzjKYJFfCeiB57q3r4Bcm.png";
    } else {
      return "https://image.tmdb.org/t/p/original/$backdropPath";
    }
  }
}

// revisar por que no me esta trayendo las urls de las imagnes. video 102
